### ISSUE TITLE
Removing [script] from hakrawler output

### ISSUE THREAD

**Issue by hakluke** [improphethacker/hakrawlerx8chain#1]
Hey in the code it looks like you're filtering out `[href]` and `[form]` but not `[script]`. It may be intentional but it doesn't look like it :) 

https://github.com/improphethacker/hakrawlerx8chain/blob/main/run.py#L16

I think you want to add `line=line.replace("[script]","")` between line 17 and 18.

**Comment by rook1337** [comment]
Thank you @hakluke for noticing this. I will add this line too.🙂
